#!/bin/sh
# ==============================================================================
# Mosquitto bridge entrypoint
# ==============================================================================
# Writes /mosquitto/bridge/bridge.conf from the MQTT_REMOTE_* variables, then
# hands off to the image's own entrypoint. mosquitto.conf includes that
# directory, so the local broker subscribes to topics on an external broker
# and republishes them locally (the equivalent of a long-running
# `mosquitto_sub -h <host> -u <user> -P <password> -t <topic>`).
#
# The file is regenerated on every start, so credentials live only in .env.
# An empty MQTT_REMOTE_HOST leaves the directory empty: no bridge.
#
#   MQTT_REMOTE_HOST       External broker hostname or IP (empty = disabled)
#   MQTT_REMOTE_PORT       Port (default: 8883 with TLS, 1883 without)
#   MQTT_REMOTE_USER       Username (optional)
#   MQTT_REMOTE_PASSWORD   Password (optional)
#   MQTT_REMOTE_TOPICS     Comma-separated topic filters to pull in (default: sensors/#)
#   MQTT_REMOTE_PREFIX     Prepended to each topic locally, e.g. remote/ (default: none)
#   MQTT_REMOTE_QOS        Subscription QoS 0-2 (default: 0)
#   MQTT_REMOTE_CLIENT_ID  Client ID on the external broker (default: p4n4-bridge-<hostname>)
#   MQTT_REMOTE_TLS        true to connect over TLS (default: false)
#   MQTT_REMOTE_CA_FILE    CA bundle; a bare name is looked up in config/mosquitto/certs/
#                          (default: the system CA bundle)
#   MQTT_REMOTE_CERT_FILE  Client certificate for mutual TLS (optional, same lookup)
#   MQTT_REMOTE_KEY_FILE   Client key for mutual TLS (optional, same lookup)
# ==============================================================================
set -eu

BRIDGE_DIR=/mosquitto/bridge
BRIDGE_CONF="$BRIDGE_DIR/bridge.conf"
CERTS_DIR=/mosquitto/certs

fail() {
    echo "p4n4 bridge: $*" >&2
    exit 1
}

# Files in config/mosquitto/certs/ may be given by name alone
cert_path() {
    case "$1" in
        /*) echo "$1" ;;
        *) echo "$CERTS_DIR/$1" ;;
    esac
}

mkdir -p "$BRIDGE_DIR"
rm -f "$BRIDGE_CONF"

host="${MQTT_REMOTE_HOST:-}"
if [ -z "$host" ]; then
    echo "p4n4 bridge: disabled (MQTT_REMOTE_HOST is empty)"
    exec /docker-entrypoint.sh "$@"
fi

tls="${MQTT_REMOTE_TLS:-false}"
case "$tls" in
    true | false) ;;
    *) fail "MQTT_REMOTE_TLS must be true or false (got '$tls')" ;;
esac

port="${MQTT_REMOTE_PORT:-}"
if [ -z "$port" ]; then
    if [ "$tls" = true ]; then port=8883; else port=1883; fi
fi
qos="${MQTT_REMOTE_QOS:-0}"
case "$qos" in
    0 | 1 | 2) ;;
    *) fail "MQTT_REMOTE_QOS must be 0, 1 or 2 (got '$qos')" ;;
esac

user="${MQTT_REMOTE_USER:-}"
password="${MQTT_REMOTE_PASSWORD:-}"
prefix="${MQTT_REMOTE_PREFIX:-}"
client_id="${MQTT_REMOTE_CLIENT_ID:-p4n4-bridge-$(hostname)}"
topics="${MQTT_REMOTE_TOPICS:-sensors/#}"

# Mosquitto reads a value up to the end of the line and a topic line is
# split on spaces, so neither may appear where they would change the meaning
for value in "$host" "$port" "$user" "$client_id" "$prefix"; do
    case "$value" in *" "*) fail "MQTT_REMOTE_* values may not contain spaces: '$value'" ;; esac
done
if [ -n "$password" ] && [ -z "$user" ]; then
    fail "MQTT_REMOTE_PASSWORD is set but MQTT_REMOTE_USER is empty"
fi

umask 077
{
    echo "# Generated by bridge.sh from MQTT_REMOTE_* at container start. Do not edit."
    echo "connection p4n4-remote"
    echo "address $host:$port"
    echo "remote_clientid $client_id"
    # Plain MQTT 3.1.1 (no Mosquitto-only bridge flag) works with any broker
    echo "bridge_protocol_version mqttv311"
    echo "try_private false"
    echo "cleansession true"
    echo "start_type automatic"
    # Publishes 1/0 to $SYS/broker/connection/p4n4-remote/state on the local
    # broker only: the external one is never written to
    echo "notifications true"
    echo "notifications_local_only true"
    echo "notification_topic \$SYS/broker/connection/p4n4-remote/state"
    if [ -n "$user" ]; then
        echo "remote_username $user"
    fi
    if [ -n "$password" ]; then
        printf 'remote_password %s\n' "$password"
    fi

    if [ "$tls" = true ]; then
        cafile="$(cert_path "${MQTT_REMOTE_CA_FILE:-/etc/ssl/certs/ca-certificates.crt}")"
        [ -r "$cafile" ] || fail "CA file not found: $cafile"
        echo "bridge_cafile $cafile"
        if [ -n "${MQTT_REMOTE_CERT_FILE:-}" ] || [ -n "${MQTT_REMOTE_KEY_FILE:-}" ]; then
            certfile="$(cert_path "${MQTT_REMOTE_CERT_FILE:-}")"
            keyfile="$(cert_path "${MQTT_REMOTE_KEY_FILE:-}")"
            [ -r "$certfile" ] && [ -r "$keyfile" ] \
                || fail "mutual TLS needs both MQTT_REMOTE_CERT_FILE and MQTT_REMOTE_KEY_FILE"
            echo "bridge_certfile $certfile"
            echo "bridge_keyfile $keyfile"
        fi
    fi

    # Inbound only: "in" subscribes on the external broker, never publishes to it
    local_prefix="${prefix:-\"\"}"
    count=0
    set -f
    old_ifs="$IFS"
    IFS=,
    for topic in $topics; do
        topic="$(echo "$topic" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
        [ -n "$topic" ] || continue
        case "$topic" in *" "*) fail "topic filters may not contain spaces: '$topic'" ;; esac
        echo "topic $topic in $qos $local_prefix \"\""
        count=$((count + 1))
    done
    IFS="$old_ifs"
    set +f
    [ "$count" -gt 0 ] || fail "MQTT_REMOTE_TOPICS has no topic filters"
} >"$BRIDGE_CONF"
# Owner-only (it holds the password), but readable by the broker after it
# drops root, so a config reload (SIGHUP) still works
if [ "$(id -u)" = 0 ]; then
    chown mosquitto:mosquitto "$BRIDGE_CONF"
fi

scheme=mqtt
[ "$tls" = true ] && scheme=mqtts
echo "p4n4 bridge: $scheme://$host:$port -> local ${prefix:-(no prefix)} [topics: $topics]"

exec /docker-entrypoint.sh "$@"
